// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"
	trainers "pokemontrainer/business/trainers"

	mock "github.com/stretchr/testify/mock"
)

// MongodbRepository is an autogenerated mock type for the MongodbRepository type
type MongodbRepository struct {
	mock.Mock
}

// LoginLog provides a mock function with given fields: ctx, trainerID
func (_m *MongodbRepository) LoginLog(ctx context.Context, trainerID uint) (trainers.Domain, error) {
	ret := _m.Called(ctx, trainerID)

	var r0 trainers.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint) trainers.Domain); ok {
		r0 = rf(ctx, trainerID)
	} else {
		r0 = ret.Get(0).(trainers.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, trainerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
